# Generated by Django 3.2 on 2021-04-21 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='タイトル')),
                ('overview', models.TextField(verbose_name='概要')),
                ('text_A', models.TextField(blank=True, verbose_name='質問文_A')),
                ('text_B', models.TextField(blank=True, verbose_name='質問文_B')),
                ('image_A', models.ImageField(blank=True, upload_to='', verbose_name='質問画像_A')),
                ('image_B', models.ImageField(blank=True, upload_to='', verbose_name='質問画像_B')),
                ('file_A', models.ImageField(blank=True, upload_to='', verbose_name='質問音声_A')),
                ('file_B', models.ImageField(blank=True, upload_to='', verbose_name='質問音声_B')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='which_one.category', verbose_name='カテゴリー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
