# Generated by Django 3.2 on 2021-04-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'アンケート', 'verbose_name_plural': 'アンケート'},
        ),
    ]
