# Generated by Django 3.2 on 2021-04-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0002_alter_questionnaire_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='コメント')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('approved_comment', models.BooleanField(default=False)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='which_one.questionnaire')),
            ],
            options={
                'verbose_name': 'コメント',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='which_one.questionnaire')),
            ],
        ),
    ]
