# Generated by Django 3.2 on 2021-04-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0003_choice_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15, verbose_name='お名前')),
                ('contact_type', models.TextField(verbose_name='種類')),
                ('contents', models.TextField(verbose_name='お問い合わせ内容')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
            },
        ),
    ]
