# Generated by Django 3.2 on 2021-04-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'カテゴリ'},
        ),
    ]
