# Generated by Django 3.2 on 2021-04-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0006_auto_20210428_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
