# Generated by Django 3.2 on 2021-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0007_auto_20210428_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name_plural': 'カテゴリ',
            },
        ),
    ]
