# Generated by Django 3.2 on 2021-04-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0010_alter_questionnaire_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='which_one.category', verbose_name='カテゴリー'),
        ),
    ]
