# Generated by Django 3.2 on 2021-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0011_alter_questionnaire_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='category',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='category',
            field=models.ManyToManyField(to='which_one.Category', verbose_name='カテゴリー'),
        ),
    ]
