# Generated by Django 3.2 on 2021-04-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0012_auto_20210428_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='category',
        ),
    ]
