# Generated by Django 3.2 on 2021-04-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0014_questionnaire_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
    ]
