# Generated by Django 3.2 on 2021-04-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0015_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='名無し', max_length=20, verbose_name='名前'),
        ),
    ]
