# Generated by Django 3.2 on 2021-04-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0016_auto_20210430_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='file_A',
            field=models.FileField(blank=True, upload_to='', verbose_name='質問音声_A'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='file_B',
            field=models.FileField(blank=True, upload_to='', verbose_name='質問音声_B'),
        ),
    ]
