# Generated by Django 3.2 on 2021-04-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0017_auto_20210430_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
