# Generated by Django 3.2 on 2021-04-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0018_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('ip_address', models.CharField(max_length=50, verbose_name='IPアドレス')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='which_one.questionnaire')),
            ],
        ),
    ]
