# Generated by Django 3.2 on 2021-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0019_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='votes_A',
        ),
        migrations.AddField(
            model_name='choice',
            name='votes_B',
            field=models.IntegerField(default=0),
        ),
    ]
