# Generated by Django 3.2 on 2021-05-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0021_auto_20210504_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
