# Generated by Django 3.2 on 2021-05-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0023_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='vote_A',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='vote_B',
            field=models.IntegerField(default=0),
        ),
    ]
