# Generated by Django 3.2 on 2021-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('which_one', '0025_alter_questionnaire_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='image_A',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='質問画像_A'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='image_B',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='質問画像_B'),
        ),
    ]
